- name: Build new testnet
  shell: |
   lcli new-testnet \
   	--spec {{ spec_preset }} \
    --deposit-contract-address {{ deposit_contract_address }} \
    --testnet-dir {{ testnetdir }} \
    --min-genesis-active-validator-count {{ genesis_validator_count }} \
    --min-genesis-time {{ genesis_time.stdout }} \
    --genesis-delay {{ genesis_delay }} \
    --genesis-fork-version {{ genesis_fork_version }} \
    --altair-fork-epoch {{ altair_fork_epoch }} \
    --bellatrix-fork-epoch {{ bellatrix_fork_epoch }} \
    --capella-fork-epoch {{ capella_fork_epoch }} \
    --deneb-fork-epoch {{ deneb_fork_epoch }} \
    --ttd {{ ttd }} \
    --eth1-block-hash {{ genesis_block_hash.stdout }} \
    --eth1-id {{ network_id }} \
    --eth1-follow-distance 128 \
    --seconds-per-slot {{ seconds_per_slot }} \
    --seconds-per-eth1-block {{ seconds_per_eth1_block }} \
    --proposer-score-boost "{{ proposer_score_boost }}" \
    --validator-count {{ genesis_validator_count }} \
    --interop-genesis-state \
    --force

- name: Generate validators
  shell: |
    lcli \
    insecure-validators \
    --count {{ validator_count }} \
    --base-dir {{ datadir }} \
    --node-count {{ nodecount }}

